Add new IDs for boards with CircuitPython just ported to them
creationid/creators pull request #66
Opened 2024-05-11 10:45 UTC by gitcnd

Assorted new boards. See (e.g.) https://github.com/adafruit/circuitpython/pull/9233

Note that some of these boards have different hardware -  e.g. ESP32-2432S028R is the restive-touch variant of the ESP32-2432S028C which already exists here as ESP32-2432S028 (  `0x00AA_0001` )

2024-05-13 22:37 UTC, tannewt requested changes
Thanks for these IDs. Just a couple requests.

2024-05-13 22:37 UTC, tannewt commented on creations/espressif.md
> +*  `0x00D0-0001` ESP32-WROVER-DEV-CAM
I don't think this should be under Espressif. Instead, make a new creation id for Freenove and make a creations/freenove.md for it.

(Espressif dev boards are documented here: https://www.espressif.com/en/products/devkits )

2024-05-13 22:37 UTC, tannewt commented on creations/sunton.md
> +*  `0x00AA_0024` [Sunton ESP32-2432S024C](https://www.aliexpress.com/item/1005005865107357.html)
This is a duplicate. Please make it unique.

2024-05-14 23:41 UTC, gitcnd commented
There is some contention over exactly who one should be listed in this PR (the designer, or the manufacturer(s), neither of which is clear from the boards themselves - I've written to try and find out who wants to front the product)

2024-05-15 18:09 UTC, tannewt commented on creations/sunton.md
> +*  `0x00AA_0024` [Sunton ESP32-2432S024C](https://www.aliexpress.com/item/1005005865107357.html)
This still looks like a duplicate of line 12.

2024-05-18 02:43 UTC, closed without merging